### ISSUE TITLE
php requirement

### ISSUE THREAD

**Issue by zetanext** [CodeAdminDe/tall-multiselect-cards#1]
Please, relax php requirement to 7.4. From what i can see woks perfectly and the component will have a much wider audience.

If you want, take a look to my fork, my usecase is insert the component in a form with other fields and I would like to use the form submit button instead of the internal component one. Surely there is a better way to do it than i did :), but i think could be useful to others also.

Thank you!

**Comment by CodeAdminDe** [comment]
Sorry, but I cannot fulfill this request. I don't want to set the requirements for any of my repositories lower than they were at the time of the first release.

Especially since I assume that the latest laravel release will also require PHP 8.0 as a minimum.

Thanks for your understanding!
