### ISSUE TITLE
Laravel 9 support

### ISSUE THREAD

**Issue by mraf** [CodeAdminDe/tall-multiselect-cards#2]
Hi could you update it to support Laravel v9?

`    - codeadminde/tall-multiselect-cards[v1.1.0, ..., v1.1.2] require laravel/framework ^8.0 -> found laravel/framework[v8.0.0, ..., 8.x-dev] but it conflicts with your root composer.json require (^9.0). `

**Comment by CodeAdminDe** [comment]
Hey @mraf,

sorry that the update is so delayed. Life got in the way ;-)

I've updated the package to version 2.0.0, which is compatible with Laravel 9 :-)
Please refer to the release notes: https://github.com/CodeAdminDe/tall-multiselect-cards/releases/tag/v2.0.0

Happy coding! :-)

Greets, CodeAdminDe
